# == In this configuration you setup Alchemy´s element layouts.
#
# For further informations please see http://guides.alchemy-cms.com/create_elements.html

- name: restaurant_and_menu
  unique: true
  hint: true
  contents:
  - name: menu_name
    type: EssenceMenu2

- name: image_slide
  picture_gallery: true

- name: center_images
  picture_gallery: true

- name: right_images
  picture_gallery: true

- name: news_ticker
  available_contents:
  - name: news_ticker_link
    type: EssenceText
    settings:
      linkable: true

- name: menu
  unique: true
  hint: true
  contents:
  - name: menu
    type: EssenceMenu

- name: menu_about
  unique: true
  contents:
  - name: menu_about_text
    type: EssenceRichtext


- name: menu_categories_and_items
  contents: 
  - name: menu_category
    type: EssenceText
  available_contents:
  - name: menu_item
    type: EssenceMenuItem

- name: restaurant_info
  contents:
  - name: restaurant_name
    type: EssenceRestaurant

- name: heading
  contents:
  - name: heading
    type: EssenceText


- name: menu_index_pictures
  picture_gallery: true

- name: about_us_text
  contents:
  - name: text
    type: EssenceRichtext

- name: about_us_images
  picture_gallery: true

- name: link
  contents:
  - name: link
    type: EssenceText
    settings:
      linkable: true
