# == In this configuration you setup Alchemy´s element layouts.
#
# For further informations please see http://guides.alchemy-cms.com/create_elements.html

- name: article
  hint: true
  unique: true
  contents:
  - name: headline
    type: EssenceText
    default: :article_headline
    hint: true
  - name: picture
    type: EssencePicture
    hint: true
  - name: text
    type: EssenceRichtext
    default: :article_text
    hint: true

- name: restaurant_and_menu
  unique: true
  contents:
  - name: menu_name
    type: EssenceMenu2

- name: left_images
  picture_gallery: true

- name: center_images
  picture_gallery: true

- name: right_images
  picture_gallery: true

- name: news_ticker
  contents:
  - name: news_ticker_link
    type: EssenceText
    settings:
      linkable: true

- name: menu
  unique: true
  contents:
  - name: menu
    hint: true
    type: EssenceMenu


- name: menu_categories_and_items
  contents: 
  - name: menu_category
    type: EssenceText
  available_contents:
  - name: menu_item
    type: EssenceMenuItem



- name: heading
  contents:
  - name: heading
    type: EssenceText


