# == This file defines the page layouts for new pages.
#
# For further informations please see http://guides.alchemy-cms.com/create_page_layouts.html

- name: index
  unique: true
  elements: [image_slide, center_images, right_images, news_ticker]
  cache: false

- name: menu_deux
  elements: [restaurant_and_menu, menu_categories_and_items]

- name: locations
  cache: false

- name: location_restaurants
  cache: false

- name: restaurant_page
  cache: false
  elements: [restaurant_info]


- name: menus_index
  elements: [menu_about, image_slide]
  cache: false

- name: menu
  elements: [menu]
  # autogenerate: [menu_example]

- name: about_us
  elements: [about_us_text, about_us_images]
  cache: false

- name: sign_up
  elements: [image_slide]

- name: gift_cards
  elements: [image_slide]

- name: contact
  elements: [image_slide, restaurant_info]

- name: look_whos_talking
  elements: [image_slide, link]